[features]
seeds = false
[programs.mainnet]
swap_program = "8vowxbBrrfDU6Dz1bBCL4W9K5pTwsBLVAd8kJPsgLiLR"
[programs.localnet]
swap_program = "8vowxbBrrfDU6Dz1bBCL4W9K5pTwsBLVAd8kJPsgLiLR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/mainnet.key"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/instructions/*.ts"
